### ISSUE TITLE
[suggestion] web terminal

### ISSUE THREAD

**Issue by pomnz1982** [elfhosted/charts#525]
### 🤪 Sanity check

- [X] I have searched and confirmed no existing [open](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue) / [closed](https://github.com/funkypenguin/geek-cookbook/issues?q=is%3Aissue+is%3Aclosed) issues, or [open](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr) / [closed](https://github.com/funkypenguin/geek-cookbook/pulls?q=is%3Apr+is%3Aclosed) PRs exist for this suggestion

### 🤕 What's not right?

The filebrowser terminal isn't all that good

### 🤯 Here's my idea!

https://xtermjs.org/ is a web terminal that looks like it'll work a lot better

### 🤔 On the other hand..

-

### 🤩 But will it fly?

-

### 💬 Your Discord username

pomnz

### 💍 Engagement

- [X] Test the changes after a preview deploy and provide feedback
- [ ] Solicit community input in [Discord](http://chat.funkypenguin.co.nz)
- [ ] Submit a PR for a first-cut myself 🏆

### ✅ Code of Conduct

- [X] I agree to follow this Geek Cookbook's Code of Conduct

**Comment by funkypenguin** [comment]
We now have [ElfTerm](https://elfhosted.com/how-to/use-elfterm/) :)
